export const ASSET_LOGOS = {
  T17O5: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  BPOD7: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  MSFT: "https://assets.cocos.capital/cocos/logos/MSFT.jpg",
  NVDA: "https://assets.cocos.capital/cocos/logos/NVDA.jpg",
  AAPL: "https://assets.cocos.capital/cocos/logos/AAPL.jpg",
  KO: "https://assets.cocos.capital/cocos/logos/KO.jpg",
  GOOGL: "https://assets.cocos.capital/cocos/logos/GOOGL.jpg",
  BMA: "https://assets.cocos.capital/cocos/logos/BMA.jpg",
  GLOB: "https://assets.cocos.capital/cocos/logos/GLNT.jpg",
  GGAL: "https://assets.cocos.capital/cocos/logos/GGAL_1.jpg",
  TGSU2: "https://assets.cocos.capital/cocos/logos/1558033661319.jpeg",
  TXAR: "https://assets.cocos.capital/cocos/logos/TXAR.jpg",
  AL30: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  CEPU: "https://assets.cocos.capital/cocos/logos/CEPU_nuevo.jpg",
  DICP: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  ALUA: "https://assets.cocos.capital/cocos/logos/ALUA.jpg",
  GD35: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  PAMP: "https://assets.cocos.capital/cocos/logos/PAMP.jpg",
  S31E5: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  MELI: "https://assets.cocos.capital/cocos/logos/MELI.jpg",
  AE38: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  GD30: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  YPFD: "https://assets.cocos.capital/cocos/logos/YPFD.jpg",
  YPFAO: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  PAMPAR: "https://assets.cocos.capital/cocos/logos/PAMP.jpg",
  TLCMO: "https://assets.cocos.capital/cocos/logos/TECO2.jpg",
  S23Y5: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  X18L5: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  S27J5: "https://assets.cocos.capital/cocos/logos/ARG.jpg",
  IRSA: "https://assets.cocos.capital/cocos/logos/IRSA.jpg",
};

export const ACTIVOS = [
  {
    id: "GGAL",
    instrumento: "accion",
    general: {
      nombre: "Grupo Financiero Galicia",
      ticker: "GGAL",
      sector: "Bancario",
      logo_emoji: "🏦",
      descripcion:
        "Uno de los principales grupos financieros de Argentina. Opera a través del Banco Galicia ofreciendo servicios bancarios, seguros y créditos.",
      ceo: "Fabián Kon",
      directivos: [
        { cargo: "CEO", nombre: "Fabián Kon" },
        { cargo: "CFO", nombre: "Hernán Berdini" },
        { cargo: "Presidente del Directorio", nombre: "Eduardo Escasany" },
      ],
    },
    precio: {
      valor: 1.85,
      moneda: "USD",
      variacion_diaria_pct: 4.2,
      variacion_ytd_pct: 31.0,
      semana_52: { min: 0.98, max: 2.1 },
      volumen_operado_ars: 125000000,
      volumen_media_30d_ars: 98000000,
      volumen_vs_media_pct: 27.6,
    },
    fundamentals: {
      market_cap_usd_mm: 2100,
      earnings_usd_mm: 184,
      earnings_periodo: "2024",
      crecimiento_ingresos_pct: 31,
      pe: 7.2,
      pb: 1.4,
      roe_pct: 19,
      dividend_yield_pct: 2.1,
      dividendo_proximo_pago: "2025-05-15",
      free_float_pct: 42,
    },
    noticias:
      "Presentó resultados anuales con aumento en depósitos. Expandió su cartera de créditos personales. El sector bancario fue afectado por cambios en la política monetaria del BCRA.",
  },
  {
    id: "BMA",
    instrumento: "accion",
    general: {
      nombre: "Banco Macro",
      ticker: "BMA",
      sector: "Bancario",
      logo_emoji: "🏛️",
      descripcion:
        "Banco privado argentino con fuerte presencia en el interior del país. Ofrece servicios financieros a individuos, empresas y al sector agropecuario.",
      ceo: "Gustavo Manriquez",
      directivos: [
        { cargo: "CEO", nombre: "Gustavo Manriquez" },
        { cargo: "CFO", nombre: "Diego Prieto" },
        { cargo: "Presidente del Directorio", nombre: "Jorge Brito (h)" },
      ],
    },
    precio: {
      valor: 2.98,
      moneda: "USD",
      variacion_diaria_pct: 1.5,
      variacion_ytd_pct: 24.0,
      semana_52: { min: 1.65, max: 3.4 },
      volumen_operado_ars: 98000000,
      volumen_media_30d_ars: 81000000,
      volumen_vs_media_pct: 21.0,
    },
    fundamentals: {
      market_cap_usd_mm: 1800,
      earnings_usd_mm: 210,
      earnings_periodo: "2024",
      crecimiento_ingresos_pct: 24,
      pe: 6.8,
      pb: 1.1,
      roe_pct: 16,
      dividend_yield_pct: 2.1,
      dividendo_proximo_pago: "2025-06-10",
      free_float_pct: 38,
    },
    noticias:
      "Anunció apertura de sucursales en nuevas provincias. Incrementó su cartera de préstamos al agro. Reportó aumento en la morosidad de créditos al consumo en el último trimestre.",
  },
  {
    id: "YPFD",
    instrumento: "accion",
    general: {
      nombre: "YPF S.A.",
      ticker: "YPFD",
      sector: "Energía / Petróleo",
      logo_emoji: "⛽",
      descripcion:
        "Principal empresa de energía de Argentina, de mayoría estatal. Extrae, refina y comercializa petróleo, gas y combustibles en todo el país.",
      ceo: "Horacio Marín",
      directivos: [
        { cargo: "CEO", nombre: "Horacio Marín" },
        { cargo: "CFO", nombre: "Federico Barroetaveña" },
      ],
    },
    precio: {
      valor: 38.5,
      moneda: "USD",
      variacion_diaria_pct: -1.1,
      variacion_ytd_pct: 18.0,
      semana_52: { min: 28.0, max: 52.0 },
      volumen_operado_ars: 340000000,
      volumen_media_30d_ars: 410000000,
      volumen_vs_media_pct: -17.1,
    },
    fundamentals: {
      market_cap_usd_mm: 15400,
      earnings_usd_mm: 1200,
      earnings_periodo: "2024",
      pe: 5.1,
      pb: 0.9,
      roe_pct: 11,
      dividend_yield_pct: 0,
      dividendo_proximo_pago: null,
    },
    noticias:
      "Continuó con la expansión de producción en Vaca Muerta. Anunció acuerdo con empresas internacionales para exportación de GNL.",
  },
  {
    id: "PAMP",
    instrumento: "accion",
    general: {
      nombre: "Pampa Energía",
      ticker: "PAMP",
      sector: "Energía",
      logo_emoji: "⚡",
      descripcion:
        "Empresa energética integrada argentina. Genera electricidad, produce gas y opera oleoductos.",
      ceo: "Gustavo Mariani",
      directivos: [
        { cargo: "CEO", nombre: "Gustavo Mariani" },
        { cargo: "CFO", nombre: "Diego Rodríguez" },
        { cargo: "Presidente del Directorio", nombre: "Marcelo Mindlin" },
      ],
    },
    precio: {
      valor: 12.4,
      moneda: "USD",
      variacion_diaria_pct: -0.4,
      variacion_ytd_pct: 12.0,
      semana_52: { min: 9.2, max: 15.8 },
      volumen_operado_ars: 210000000,
      volumen_media_30d_ars: 190000000,
      volumen_vs_media_pct: 10.5,
    },
    fundamentals: {
      market_cap_usd_mm: 3700,
      earnings_usd_mm: 320,
      earnings_periodo: "2024",
      pe: 9.3,
      pb: 1.6,
      roe_pct: 14,
      dividend_yield_pct: 0,
      dividendo_proximo_pago: null,
    },
    noticias:
      "Finalizó obras de ampliación en planta de ciclo combinado. El gobierno revisó tarifas eléctricas afectando ingresos proyectados.",
  },
  {
    id: "TXAR",
    instrumento: "accion",
    general: {
      nombre: "Ternium Argentina",
      ticker: "TXAR",
      sector: "Industria / Acero",
      logo_emoji: "🏗️",
      descripcion:
        "Productora de acero plano y productos de hierro. Abastece a las industrias automotriz, de la construcción y electrodomésticos.",
      ceo: "Máximo Vedoya",
      directivos: [
        { cargo: "CEO Regional", nombre: "Máximo Vedoya" },
        { cargo: "CFO", nombre: "Pablo Brizzio" },
      ],
    },
    precio: {
      valor: 8.75,
      moneda: "USD",
      variacion_diaria_pct: 0.8,
      variacion_ytd_pct: -8.0,
      semana_52: { min: 6.1, max: 11.2 },
      volumen_operado_ars: 55000000,
      volumen_media_30d_ars: 62000000,
      volumen_vs_media_pct: -11.3,
    },
    fundamentals: {
      market_cap_usd_mm: 890,
      earnings_usd_mm: -45,
      earnings_periodo: "2024",
      pe: null,
      pb: 0.7,
      roe_pct: -4,
      dividend_yield_pct: 0,
      dividendo_proximo_pago: null,
    },
    noticias:
      "La caída en la actividad de la construcción redujo la demanda de acero. Exportó volúmenes récord a Brasil.",
  },
  {
    id: "ALUA",
    instrumento: "accion",
    general: {
      nombre: "Aluar Aluminio Argentino",
      ticker: "ALUA",
      sector: "Industria / Aluminio",
      logo_emoji: "🔩",
      descripcion:
        "Única productora de aluminio primario de Argentina. Exporta más del 70% de su producción.",
      ceo: "Martín Berardi",
      directivos: [
        { cargo: "CEO", nombre: "Martín Berardi" },
        {
          cargo: "Presidente del Directorio",
          nombre: "Javier Madanes Quintanilla",
        },
      ],
    },
    precio: {
      valor: 1.45,
      moneda: "USD",
      variacion_diaria_pct: 2.3,
      variacion_ytd_pct: 9.0,
      semana_52: { min: 0.98, max: 1.82 },
      volumen_operado_ars: 88000000,
      volumen_media_30d_ars: 74000000,
      volumen_vs_media_pct: 18.9,
    },
    fundamentals: {
      market_cap_usd_mm: 950,
      earnings_usd_mm: 95,
      earnings_periodo: "2024",
      pe: 10.1,
      pb: 1.3,
      roe_pct: 12,
      dividend_yield_pct: 3.2,
      dividendo_proximo_pago: "2025-04-22",
    },
    noticias:
      "Se benefició de la suba del aluminio en mercados internacionales. Anunció plan de inversión en capacidad productiva.",
  },
  {
    id: "CEPU",
    instrumento: "accion",
    general: {
      nombre: "Central Puerto",
      ticker: "CEPU",
      sector: "Energía / Generación Eléctrica",
      logo_emoji: "🔌",
      descripcion:
        "Mayor generadora termoeléctrica privada de Argentina. Opera centrales de ciclo combinado, turbovapor y turbinas de gas.",
      ceo: "Gabriel Cohen",
      directivos: [
        { cargo: "CEO", nombre: "Gabriel Cohen" },
        { cargo: "CFO", nombre: "Matías Mosse" },
      ],
    },
    precio: {
      valor: 6.8,
      moneda: "USD",
      variacion_diaria_pct: 1.2,
      variacion_ytd_pct: 15.0,
      semana_52: { min: 4.9, max: 8.4 },
      volumen_operado_ars: 72000000,
      volumen_media_30d_ars: 65000000,
      volumen_vs_media_pct: 10.8,
    },
    fundamentals: {
      market_cap_usd_mm: 1100,
      earnings_usd_mm: 130,
      earnings_periodo: "2024",
      pe: 8.5,
      pb: 1.2,
      roe_pct: 13,
      dividend_yield_pct: 4.0,
      dividendo_proximo_pago: "2025-05-08",
    },
    noticias:
      "Ganó licitaciones para nueva capacidad de generación. Anunció dividendo extraordinario por resultados del año.",
  },
  {
    id: "TGSU2",
    instrumento: "accion",
    general: {
      nombre: "Transportadora de Gas del Sur",
      ticker: "TGSU2",
      sector: "Energía / Gas",
      logo_emoji: "🔧",
      descripcion:
        "Opera el mayor sistema de transporte de gas natural de Argentina. Conecta Neuquén y el sur del país con Buenos Aires.",
      ceo: "Alejandro Basso",
      directivos: [
        { cargo: "CEO", nombre: "Alejandro Basso" },
        { cargo: "Presidente del Directorio", nombre: "Sebastián Tempone" },
      ],
    },
    precio: {
      valor: 3.2,
      moneda: "USD",
      variacion_diaria_pct: 0.5,
      variacion_ytd_pct: 22.0,
      semana_52: { min: 2.1, max: 4.1 },
      volumen_operado_ars: 61000000,
      volumen_media_30d_ars: 54000000,
      volumen_vs_media_pct: 13.0,
    },
    fundamentals: {
      market_cap_usd_mm: 850,
      earnings_usd_mm: 110,
      earnings_periodo: "2024",
      pe: 7.7,
      pb: 1.1,
      roe_pct: 15,
      dividend_yield_pct: 3.5,
      dividendo_proximo_pago: "2025-06-01",
    },
    noticias:
      "Renegociación tarifaria con ENARGAS mejoró perspectivas de ingresos. Expansión de gasoducto Néstor Kirchner beneficia sus flujos.",
  },
  {
    id: "MELI",
    instrumento: "cedear",
    general: {
      nombre: "MercadoLibre",
      ticker: "MELI",
      sector: "Tecnología / E-commerce",
      logo_emoji: "🛒",
      descripcion:
        "La plataforma de e-commerce y pagos más grande de Latinoamérica. Opera en 18 países con marketplace, Mercado Pago y logística propia.",
      ceo: "Marcos Galperin",
      directivos: [
        { cargo: "CEO", nombre: "Marcos Galperin" },
        { cargo: "CFO", nombre: "Martín de los Santos" },
      ],
    },
    precio: {
      valor: 2150000,
      moneda: "ARS",
      subyacente_usd: 2150,
      variacion_diaria_pct: 2.8,
      variacion_ytd_pct: 18.5,
      semana_52: { min: 1480000, max: 2380000 },
      volumen_operado_ars: 430000000,
      volumen_media_30d_ars: 380000000,
      volumen_vs_media_pct: 13.2,
    },
    cedear_info: { ratio_cedear: 1, bolsa_origen: "NASDAQ" },
    fundamentals: {
      market_cap_usd_mm: 109000,
      earnings_usd_mm: 4800,
      earnings_periodo: "2024",
      pe: 58,
      pb: 18.2,
      roe_pct: 31,
      dividend_yield_pct: 0,
      dividendo_proximo_pago: null,
    },
    noticias:
      "Reportó crecimiento récord en volumen de pagos digitales. Mercado Crédito superó los 50 millones de préstamos otorgados.",
  },
  {
    id: "AAPL",
    instrumento: "cedear",
    general: {
      nombre: "Apple Inc.",
      ticker: "AAPL",
      sector: "Tecnología",
      logo_emoji: "🍎",
      descripcion:
        "La empresa de tecnología más valiosa del mundo. Fabrica iPhone, Mac y servicios digitales.",
      ceo: "Tim Cook",
      directivos: [
        { cargo: "CEO", nombre: "Tim Cook" },
        { cargo: "CFO", nombre: "Luca Maestri" },
      ],
    },
    precio: {
      valor: 187000,
      moneda: "ARS",
      subyacente_usd: 187,
      variacion_diaria_pct: 0.6,
      variacion_ytd_pct: 9.2,
      semana_52: { min: 142000, max: 210000 },
      volumen_operado_ars: 215000000,
      volumen_media_30d_ars: 195000000,
      volumen_vs_media_pct: 10.3,
    },
    cedear_info: { ratio_cedear: 8, bolsa_origen: "NASDAQ" },
    fundamentals: {
      market_cap_usd_mm: 2900000,
      earnings_usd_mm: 97000,
      earnings_periodo: "FY2024",
      pe: 29.1,
      pb: 47.3,
      roe_pct: 160,
      dividend_yield_pct: 0.5,
      dividendo_proximo_pago: "2025-02-13",
    },
    noticias:
      "Presentó resultados del Q1 2025 superando expectativas. Apple Intelligence impulsó ventas de iPhone 16.",
  },
  {
    id: "MSFT",
    instrumento: "cedear",
    general: {
      nombre: "Microsoft Corporation",
      ticker: "MSFT",
      sector: "Tecnología",
      logo_emoji: "🪟",
      descripcion:
        "Líder global en software, servicios en la nube Azure e inteligencia artificial con Copilot.",
      ceo: "Satya Nadella",
      directivos: [
        { cargo: "CEO", nombre: "Satya Nadella" },
        { cargo: "CFO", nombre: "Amy Hood" },
      ],
    },
    precio: {
      valor: 412000,
      moneda: "ARS",
      subyacente_usd: 412,
      variacion_diaria_pct: 0.7,
      variacion_ytd_pct: 16.0,
      semana_52: { min: 320000, max: 478000 },
      volumen_operado_ars: 285000000,
      volumen_media_30d_ars: 260000000,
      volumen_vs_media_pct: 9.6,
    },
    cedear_info: { ratio_cedear: 10, bolsa_origen: "NASDAQ" },
    fundamentals: {
      market_cap_usd_mm: 3060000,
      earnings_usd_mm: 88100,
      earnings_periodo: "FY2024",
      pe: 35,
      pb: 13.2,
      roe_pct: 38,
      dividend_yield_pct: 0.8,
      dividendo_proximo_pago: "2025-03-13",
    },
    noticias:
      "Copilot integrado en toda la suite Office. Azure creció 29% anual. Inversión en OpenAI sigue generando retornos.",
  },
  {
    id: "NVDA",
    instrumento: "cedear",
    general: {
      nombre: "NVIDIA Corporation",
      ticker: "NVDA",
      sector: "Tecnología / Semiconductores",
      logo_emoji: "🟢",
      descripcion:
        "Líder mundial en chips de inteligencia artificial, GPUs y plataformas de computación acelerada.",
      ceo: "Jensen Huang",
      directivos: [
        { cargo: "CEO", nombre: "Jensen Huang" },
        { cargo: "CFO", nombre: "Colette Kress" },
      ],
    },
    precio: {
      valor: 115000,
      moneda: "ARS",
      subyacente_usd: 115,
      variacion_diaria_pct: 3.5,
      variacion_ytd_pct: 114.0,
      semana_52: { min: 68000, max: 142000 },
      volumen_operado_ars: 510000000,
      volumen_media_30d_ars: 445000000,
      volumen_vs_media_pct: 14.6,
    },
    cedear_info: { ratio_cedear: 10, bolsa_origen: "NASDAQ" },
    fundamentals: {
      market_cap_usd_mm: 2820000,
      earnings_usd_mm: 72880,
      earnings_periodo: "FY2025",
      pe: 52,
      pb: 32.5,
      roe_pct: 63,
      dividend_yield_pct: 0.1,
      dividendo_proximo_pago: "2025-03-28",
    },
    noticias:
      "Demanda de chips H100/H200 para centros de datos de IA supera la oferta. Blackwell architecture en producción masiva.",
  },
  {
    id: "GOOGL",
    instrumento: "cedear",
    general: {
      nombre: "Alphabet Inc. (Google)",
      ticker: "GOOGL",
      sector: "Tecnología",
      logo_emoji: "🔵",
      descripcion:
        "Dueña de Google, YouTube, Google Cloud y Waymo. Líder global en búsqueda online y publicidad digital.",
      ceo: "Sundar Pichai",
      directivos: [
        { cargo: "CEO", nombre: "Sundar Pichai" },
        { cargo: "CFO", nombre: "Anat Ashkenazi" },
      ],
    },
    precio: {
      valor: 176000,
      moneda: "ARS",
      subyacente_usd: 176,
      variacion_diaria_pct: 0.9,
      variacion_ytd_pct: 14.0,
      semana_52: { min: 128000, max: 204000 },
      volumen_operado_ars: 198000000,
      volumen_media_30d_ars: 178000000,
      volumen_vs_media_pct: 11.2,
    },
    cedear_info: { ratio_cedear: 10, bolsa_origen: "NASDAQ" },
    fundamentals: {
      market_cap_usd_mm: 2180000,
      earnings_usd_mm: 73800,
      earnings_periodo: "FY2024",
      pe: 22,
      pb: 7.1,
      roe_pct: 32,
      dividend_yield_pct: 0.5,
      dividendo_proximo_pago: "2025-03-27",
    },
    noticias:
      "Avances en IA con Gemini. Crecimiento acelerado en Google Cloud. Litigios antimonopolio en EE.UU.",
  },
  {
    id: "GLOB",
    instrumento: "cedear",
    general: {
      nombre: "Globant S.A.",
      ticker: "GLOB",
      sector: "Tecnología / IT Services",
      logo_emoji: "🌐",
      descripcion:
        "Empresa tecnológica de origen argentino líder en servicios digitales y transformación tecnológica. Cotiza en NYSE.",
      ceo: "Martín Migoya",
      directivos: [
        { cargo: "CEO", nombre: "Martín Migoya" },
        { cargo: "CFO", nombre: "Juan Urthiague" },
      ],
    },
    precio: {
      valor: 182000,
      moneda: "ARS",
      subyacente_usd: 182,
      variacion_diaria_pct: 1.9,
      variacion_ytd_pct: 18.0,
      semana_52: { min: 135000, max: 220000 },
      volumen_operado_ars: 110000000,
      volumen_media_30d_ars: 92000000,
      volumen_vs_media_pct: 19.6,
    },
    cedear_info: { ratio_cedear: 10, bolsa_origen: "NYSE" },
    fundamentals: {
      market_cap_usd_mm: 7100,
      earnings_usd_mm: 185,
      earnings_periodo: "2024",
      pe: 37,
      pb: 5.8,
      roe_pct: 16,
      dividend_yield_pct: 0,
      dividendo_proximo_pago: null,
    },
    noticias:
      "Ganó contratos con Disney y FIFA para plataformas digitales. Aceleró contratación en Latinoamérica.",
  },
  {
    id: "KO",
    instrumento: "cedear",
    general: {
      nombre: "The Coca-Cola Company",
      ticker: "KO",
      sector: "Consumo / Bebidas",
      logo_emoji: "🥤",
      descripcion:
        "Líder global en bebidas no alcohólicas. Distribuye más de 500 marcas en más de 200 países.",
      ceo: "James Quincey",
      directivos: [
        { cargo: "CEO", nombre: "James Quincey" },
        { cargo: "CFO", nombre: "John Murphy" },
      ],
    },
    precio: {
      valor: 62000,
      moneda: "ARS",
      subyacente_usd: 62,
      variacion_diaria_pct: 0.3,
      variacion_ytd_pct: 3.0,
      semana_52: { min: 51000, max: 72000 },
      volumen_operado_ars: 75000000,
      volumen_media_30d_ars: 68000000,
      volumen_vs_media_pct: 10.3,
    },
    cedear_info: { ratio_cedear: 10, bolsa_origen: "NYSE" },
    fundamentals: {
      market_cap_usd_mm: 268000,
      earnings_usd_mm: 10600,
      earnings_periodo: "2024",
      pe: 24,
      pb: 10.9,
      roe_pct: 45,
      dividend_yield_pct: 3.1,
      dividendo_proximo_pago: "2025-04-01",
    },
    noticias:
      "Aumentó precios en mercados emergentes. Dividendo sostenido por 60 años consecutivos.",
  },
  {
    id: "GD30",
    instrumento: "bono_soberano",
    general: {
      nombre: "Bono Soberano Global 2030",
      ticker: "GD30",
      sector: "Deuda Soberana",
      logo_emoji: "📄",
      descripcion:
        "Bono del Estado Nacional argentino bajo ley de Nueva York con vencimiento en 2030.",
      emisor: "República Argentina",
    },
    precio: {
      valor: 70.8,
      moneda: "USD",
      variacion_diaria_pct: 0.9,
      variacion_ytd_pct: 12.3,
      semana_52: { min: 55, max: 78 },
      volumen_operado_ars: 890000000,
    },
    bono_info: {
      tir_pct: 10.8,
      duracion_anios: 4.1,
      vencimiento: "2030-07-09",
      cupon_pct: 0.5,
      ley: "Nueva York",
      paridad_pct: 70.8,
      calificacion_crediticia: "CCC",
      amortizacion: "Semestral desde 2024",
      proximo_pago_cupon: "2025-07-09",
      proximo_pago_monto_usd: 2.5,
    },
    noticias:
      "El riesgo país bajó 40 puntos tras acuerdo con FMI. Fuerte demanda de inversores locales e internacionales.",
  },
  {
    id: "AL30",
    instrumento: "bono_soberano",
    general: {
      nombre: "Bono Soberano Argentina 2030 (Ley Argentina)",
      ticker: "AL30",
      sector: "Deuda Soberana",
      logo_emoji: "📄",
      descripcion:
        "Bono soberano bajo ley argentina con vencimiento en 2030. Mismo flujo que GD30 pero menor protección legal.",
      emisor: "República Argentina",
    },
    precio: {
      valor: 68.5,
      moneda: "USD",
      variacion_diaria_pct: 0.7,
      variacion_ytd_pct: 11.5,
      semana_52: { min: 52, max: 76 },
      volumen_operado_ars: 1200000000,
    },
    bono_info: {
      tir_pct: 11.2,
      duracion_anios: 4.1,
      vencimiento: "2030-07-09",
      cupon_pct: 0.5,
      ley: "Argentina",
      paridad_pct: 68.5,
      calificacion_crediticia: "CCC",
      amortizacion: "Semestral desde 2024",
      proximo_pago_cupon: "2025-07-09",
      proximo_pago_monto_usd: 2.5,
    },
    noticias: "Spread soberano se comprimió. Alta liquidez en mercado local.",
  },
  {
    id: "GD35",
    instrumento: "bono_soberano",
    general: {
      nombre: "Bono Soberano Global 2035",
      ticker: "GD35",
      sector: "Deuda Soberana",
      logo_emoji: "📄",
      descripcion:
        "Bono soberano argentino bajo ley de Nueva York con vencimiento en 2035. Mayor duration que GD30.",
      emisor: "República Argentina",
    },
    precio: {
      valor: 64.2,
      moneda: "USD",
      variacion_diaria_pct: 1.0,
      variacion_ytd_pct: 14.1,
      semana_52: { min: 48, max: 72 },
      volumen_operado_ars: 620000000,
    },
    bono_info: {
      tir_pct: 11.7,
      duracion_anios: 6.8,
      vencimiento: "2035-07-09",
      cupon_pct: 3.625,
      ley: "Nueva York",
      paridad_pct: 64.2,
      calificacion_crediticia: "CCC",
      amortizacion: "Semestral desde 2029",
      proximo_pago_cupon: "2025-07-09",
      proximo_pago_monto_usd: 18.13,
    },
    noticias: "Fuerte interés de inversores extranjeros en la curva larga.",
  },
  {
    id: "AE38",
    instrumento: "bono_soberano",
    general: {
      nombre: "Bono Soberano Argentina 2038 (Ley Local)",
      ticker: "AE38",
      sector: "Deuda Soberana",
      logo_emoji: "📄",
      descripcion:
        "Bono soberano de largo plazo bajo ley local con vencimiento en 2038. Cupones crecientes.",
      emisor: "República Argentina",
    },
    precio: {
      valor: 58.1,
      moneda: "USD",
      variacion_diaria_pct: 0.5,
      variacion_ytd_pct: 10.8,
      semana_52: { min: 42, max: 65 },
      volumen_operado_ars: 380000000,
    },
    bono_info: {
      tir_pct: 12.9,
      duracion_anios: 8.2,
      vencimiento: "2038-01-09",
      cupon_pct: 4.25,
      ley: "Argentina",
      paridad_pct: 58.1,
      calificacion_crediticia: "CCC",
      amortizacion: "Bullet",
      proximo_pago_cupon: "2026-01-09",
      proximo_pago_monto_usd: 21.25,
    },
    noticias:
      "El tramo ultra largo tiene mayor volatilidad pero potencial de upside ante mejora del riesgo país.",
  },
  {
    id: "DICP",
    instrumento: "bono_soberano",
    general: {
      nombre: "Discount CER Ley Local",
      ticker: "DICP",
      sector: "Deuda Soberana",
      logo_emoji: "📄",
      descripcion:
        "Bono soberano ajustado por CER (inflación). Emitido en el canje de 2005, vence en 2033.",
      emisor: "República Argentina",
    },
    precio: {
      valor: 480,
      moneda: "ARS",
      variacion_diaria_pct: 0.3,
      variacion_ytd_pct: 9.5,
      semana_52: { min: 380, max: 520 },
      volumen_operado_ars: 290000000,
    },
    bono_info: {
      tir_pct: 8.1,
      duracion_anios: 5.3,
      vencimiento: "2033-12-31",
      cupon_pct: 5.83,
      ley: "Argentina",
      paridad_pct: 105.2,
      calificacion_crediticia: "CCC",
      amortizacion: "Semestral",
      proximo_pago_cupon: "2025-06-30",
      tipo_ajuste: "CER",
    },
    noticias:
      "Sube la demanda de instrumentos CER ante expectativas de inflación persistente.",
  },
  {
    id: "BPOD7",
    instrumento: "bono_soberano",
    general: {
      nombre: "Bono Provincia de Buenos Aires 2027",
      ticker: "BPOD7",
      sector: "Deuda Provincial",
      logo_emoji: "📄",
      descripcion:
        "Bono de la Provincia de Buenos Aires bajo ley local con vencimiento en 2027.",
      emisor: "Provincia de Buenos Aires",
    },
    precio: {
      valor: 74.2,
      moneda: "USD",
      variacion_diaria_pct: 0.4,
      variacion_ytd_pct: 8.2,
      semana_52: { min: 58, max: 80 },
      volumen_operado_ars: 145000000,
    },
    bono_info: {
      tir_pct: 13.8,
      duracion_anios: 2.6,
      vencimiento: "2027-05-01",
      cupon_pct: 5.25,
      ley: "Argentina",
      paridad_pct: 74.2,
      calificacion_crediticia: "CCC-",
      amortizacion: "Bullet",
      proximo_pago_cupon: "2025-05-01",
      proximo_pago_monto_usd: 26.25,
    },
    noticias:
      "Provincia refinanció parte de su deuda en 2024. Coparticipación como garantía reduce riesgo relativo.",
  },
  {
    id: "YPF-ON-2027",
    instrumento: "on",
    general: {
      nombre: "YPF ON Serie XLIII 2027",
      ticker: "YPFAO",
      sector: "Energía / Petróleo",
      logo_emoji: "🏢",
      descripcion:
        "Obligación negociable hard dollar de YPF garantizada con flujos de exportación.",
      empresa_emisora: "YPF S.A.",
      ceo: "Horacio Marín",
      directivos: [
        { cargo: "CEO", nombre: "Horacio Marín" },
        { cargo: "CFO", nombre: "Federico Barroetaveña" },
      ],
    },
    precio: {
      valor: 98.5,
      moneda: "USD",
      variacion_diaria_pct: 0.2,
      variacion_ytd_pct: 5.1,
      semana_52: { min: 88, max: 102 },
      volumen_operado_ars: 95000000,
    },
    on_info: {
      tir_pct: 8.5,
      duracion_anios: 2.1,
      vencimiento: "2027-03-15",
      cupon_pct: 8.5,
      ley: "Argentina",
      calificacion_crediticia: "B-",
      garantia: "Exportaciones de petróleo",
      proximo_pago_cupon: "2025-03-15",
      proximo_pago_monto_usd: 4.25,
    },
    noticias:
      "Muy demandada por garantía exportadora y rendimiento en dólares.",
  },
  {
    id: "PAMPA-ON-2027",
    instrumento: "on",
    general: {
      nombre: "Pampa Energía ON USD 2027",
      ticker: "PAMPAR",
      sector: "Energía",
      logo_emoji: "🏢",
      descripcion:
        "Obligación Negociable en dólares de Pampa Energía. Una de las ONs corporativas más líquidas del mercado.",
      empresa_emisora: "Pampa Energía S.A.",
      ceo: "Gustavo Mariani",
      directivos: [{ cargo: "CEO", nombre: "Gustavo Mariani" }],
    },
    precio: {
      valor: 102.4,
      moneda: "USD",
      variacion_diaria_pct: 0.2,
      variacion_ytd_pct: 6.8,
      semana_52: { min: 92, max: 106 },
      volumen_operado_ars: 68000000,
    },
    on_info: {
      tir_pct: 7.2,
      duracion_anios: 2.8,
      vencimiento: "2027-09-22",
      cupon_pct: 7.5,
      ley: "Nueva York",
      calificacion_crediticia: "B",
      garantia: "Quirografaria",
      proximo_pago_cupon: "2025-09-22",
      proximo_pago_monto_usd: 3.75,
    },
    noticias: "Cotiza sobre la par por sólida posición financiera.",
  },
  {
    id: "TELECOM-ON-2026",
    instrumento: "on",
    general: {
      nombre: "Telecom Argentina ON USD 2026",
      ticker: "TLCMO",
      sector: "Telecomunicaciones",
      logo_emoji: "🏢",
      descripcion:
        "ON en dólares de la mayor empresa de telecomunicaciones de Argentina.",
      empresa_emisora: "Telecom Argentina S.A.",
      ceo: "Carlos Moltini",
      directivos: [
        { cargo: "CEO", nombre: "Carlos Moltini" },
        { cargo: "CFO", nombre: "Gabriel Blasi" },
      ],
    },
    precio: {
      valor: 97.8,
      moneda: "USD",
      variacion_diaria_pct: 0.2,
      variacion_ytd_pct: 4.9,
      semana_52: { min: 88, max: 102 },
      volumen_operado_ars: 42000000,
    },
    on_info: {
      tir_pct: 9.1,
      duracion_anios: 1.3,
      vencimiento: "2026-03-17",
      cupon_pct: 8.5,
      ley: "Nueva York",
      calificacion_crediticia: "B-",
      garantia: "Quirografaria",
      proximo_pago_cupon: "2025-03-17",
      proximo_pago_monto_usd: 4.25,
    },
    noticias: "La empresa mejoró su flujo de caja por ajuste tarifario.",
  },
  {
    id: "ARCOR-ON-2027",
    instrumento: "on",
    general: {
      nombre: "Arcor ON USD 2027",
      ticker: "ARCABO",
      sector: "Consumo / Alimentos",
      logo_emoji: "🏢",
      descripcion:
        "Obligación Negociable de Arcor, líder en alimentos y confitería de Latinoamérica.",
      empresa_emisora: "Arcor S.A.I.C.",
      ceo: "Daniel Funes de Rioja",
      directivos: [
        { cargo: "Presidente y CEO", nombre: "Daniel Funes de Rioja" },
        { cargo: "CFO", nombre: "Pablo Campana" },
      ],
    },
    precio: {
      valor: 99.2,
      moneda: "USD",
      variacion_diaria_pct: 0.1,
      variacion_ytd_pct: 3.8,
      semana_52: { min: 90, max: 104 },
      volumen_operado_ars: 31000000,
    },
    on_info: {
      tir_pct: 7.8,
      duracion_anios: 2.2,
      vencimiento: "2027-01-22",
      cupon_pct: 6.0,
      ley: "Nueva York",
      calificacion_crediticia: "B",
      garantia: "Quirografaria",
      proximo_pago_cupon: "2025-07-22",
      proximo_pago_monto_usd: 3.0,
    },
    noticias: "Perfil exportador da solidez al crédito.",
  },
  {
    id: "GENNEIA-ON-2027",
    instrumento: "on",
    general: {
      nombre: "Genneia ON USD 2027",
      ticker: "GNCXO",
      sector: "Energías Renovables",
      logo_emoji: "🌿",
      descripcion:
        "ON de Genneia, mayor empresa de generación de energía renovable de Argentina.",
      empresa_emisora: "Genneia S.A.",
      ceo: "Juan Bosch",
      directivos: [
        { cargo: "CEO", nombre: "Juan Bosch" },
        { cargo: "CFO", nombre: "Analía Colombo" },
      ],
    },
    precio: {
      valor: 90.1,
      moneda: "USD",
      variacion_diaria_pct: 0.6,
      variacion_ytd_pct: 7.2,
      semana_52: { min: 80, max: 98 },
      volumen_operado_ars: 28000000,
    },
    on_info: {
      tir_pct: 11.9,
      duracion_anios: 2.7,
      vencimiento: "2027-09-12",
      cupon_pct: 8.75,
      ley: "Nueva York",
      calificacion_crediticia: "B-",
      garantia: "Contratos PPA con CAMMESA",
      proximo_pago_cupon: "2025-09-12",
      proximo_pago_monto_usd: 4.38,
    },
    noticias: "La transición energética global respalda el perfil.",
  },
  {
    id: "IRSA-ON-2028",
    instrumento: "on",
    general: {
      nombre: "IRSA Propiedades Comerciales ON USD 2028",
      ticker: "IRCFO",
      sector: "Real Estate",
      logo_emoji: "🏢",
      descripcion:
        "ON en dólares de la principal operadora de shoppings y real estate comercial de Argentina.",
      empresa_emisora: "IRSA Propiedades Comerciales S.A.",
      ceo: "Alejandro Elsztain",
      directivos: [
        { cargo: "CEO", nombre: "Alejandro Elsztain" },
        { cargo: "Presidente", nombre: "Eduardo Elsztain" },
      ],
    },
    precio: {
      valor: 94.2,
      moneda: "USD",
      variacion_diaria_pct: -0.1,
      variacion_ytd_pct: 6.1,
      semana_52: { min: 84, max: 100 },
      volumen_operado_ars: 22000000,
    },
    on_info: {
      tir_pct: 9.8,
      duracion_anios: 3.2,
      vencimiento: "2028-03-15",
      cupon_pct: 8.75,
      ley: "Nueva York",
      calificacion_crediticia: "B-",
      garantia: "Quirografaria",
      proximo_pago_cupon: "2025-09-15",
      proximo_pago_monto_usd: 4.38,
    },
    noticias: "Los shopping centers recuperaron tráfico y facturación.",
  },
  {
    id: "S31E5",
    instrumento: "letra",
    general: {
      nombre: "LECAP Enero 2025",
      ticker: "S31E5",
      sector: "Deuda Soberana",
      logo_emoji: "🏛️",
      descripcion:
        "Letra Capitalizable del Tesoro Nacional en pesos a tasa fija.",
      emisor: "Ministerio de Economía",
    },
    precio: {
      valor: 98.2,
      moneda: "ARS",
      variacion_diaria_pct: 0.1,
      variacion_ytd_pct: 8.4,
      semana_52: { min: 90, max: 100 },
      volumen_operado_ars: 320000000,
    },
    letra_info: {
      vencimiento: "2025-01-31",
      dias_al_vencimiento: 19,
      tipo_ajuste: "Tasa fija",
      tna_pct: 33.0,
      tea_pct: 38.5,
      benchmark: {
        tipo: "TNA Plazo fijo",
        valor_pct: 24.5,
        spread_vs_benchmark_pct: 8.5,
      },
    },
    noticias: null,
  },
  {
    id: "S23Y5",
    instrumento: "letra",
    general: {
      nombre: "LECAP Mayo 2025",
      ticker: "S23Y5",
      sector: "Deuda Soberana",
      logo_emoji: "🏛️",
      descripcion:
        "Letra Capitalizable del Tesoro en pesos a tasa fija con vencimiento en mayo 2025.",
      emisor: "Ministerio de Economía",
    },
    precio: {
      valor: 1124,
      moneda: "ARS",
      variacion_diaria_pct: 0.08,
      variacion_ytd_pct: 11.2,
      semana_52: { min: 900, max: 1200 },
      volumen_operado_ars: 480000000,
    },
    letra_info: {
      vencimiento: "2025-05-23",
      dias_al_vencimiento: 72,
      tipo_ajuste: "Tasa fija",
      tna_pct: 34.0,
      tea_pct: 39.8,
      benchmark: {
        tipo: "TNA Plazo fijo",
        valor_pct: 24.5,
        spread_vs_benchmark_pct: 9.5,
      },
    },
    noticias:
      "Las LECAPs se posicionaron como referencia de tasa fija en pesos.",
  },
  {
    id: "TZXM5",
    instrumento: "letra",
    general: {
      nombre: "LECER Marzo 2025",
      ticker: "TZXM5",
      sector: "Deuda Soberana",
      logo_emoji: "🏛️",
      descripcion:
        "Letra del Tesoro ajustada por CER (inflación) con vencimiento en marzo 2025.",
      emisor: "Ministerio de Economía",
    },
    precio: {
      valor: 97.8,
      moneda: "ARS",
      variacion_diaria_pct: 0.2,
      variacion_ytd_pct: 11.2,
      semana_52: { min: 85, max: 100 },
      volumen_operado_ars: 180000000,
    },
    letra_info: {
      vencimiento: "2025-03-21",
      dias_al_vencimiento: 9,
      tipo_ajuste: "CER (inflación)",
      tir_real_pct: 2.1,
      benchmark: {
        tipo: "Inflación mensual",
        valor_pct: 2.4,
        spread_vs_benchmark_pct: -0.3,
      },
    },
    noticias: null,
  },
  {
    id: "X18L5",
    instrumento: "letra",
    general: {
      nombre: "LECER Julio 2025",
      ticker: "X18L5",
      sector: "Deuda Soberana",
      logo_emoji: "🏛️",
      descripcion:
        "Letra del Tesoro ajustada por CER con vencimiento en julio 2025.",
      emisor: "Ministerio de Economía",
    },
    precio: {
      valor: 1210,
      moneda: "ARS",
      variacion_diaria_pct: 0.12,
      variacion_ytd_pct: 14.8,
      semana_52: { min: 980, max: 1280 },
      volumen_operado_ars: 390000000,
    },
    letra_info: {
      vencimiento: "2025-07-18",
      dias_al_vencimiento: 128,
      tipo_ajuste: "CER (inflación)",
      tir_real_pct: 3.2,
      benchmark: {
        tipo: "Inflación mensual",
        valor_pct: 2.4,
        spread_vs_benchmark_pct: 0.8,
      },
    },
    noticias:
      "Alta demanda de instrumentos CER ante incertidumbre inflacionaria.",
  },
  {
    id: "S27J5",
    instrumento: "letra",
    general: {
      nombre: "LEDE Junio 2025",
      ticker: "S27J5",
      sector: "Deuda Soberana",
      logo_emoji: "🏛️",
      descripcion:
        "Letra del Tesoro en dólares con descuento y vencimiento en junio 2025.",
      emisor: "Ministerio de Economía",
    },
    precio: {
      valor: 98.4,
      moneda: "USD",
      variacion_diaria_pct: 0.05,
      variacion_ytd_pct: 3.2,
      semana_52: { min: 93, max: 100 },
      volumen_operado_ars: 210000000,
    },
    letra_info: {
      vencimiento: "2025-06-27",
      dias_al_vencimiento: 107,
      tipo_ajuste: "Tasa fija USD",
      tna_pct: 5.8,
      tea_pct: 5.9,
      benchmark: {
        tipo: "Fed Funds Rate",
        valor_pct: 5.25,
        spread_vs_benchmark_pct: 0.55,
      },
    },
    noticias: "Alta demanda en la última licitación.",
  },
  {
    id: "T17O5",
    instrumento: "letra",
    general: {
      nombre: "Letra Dólar Linked Octubre 2025",
      ticker: "T17O5",
      sector: "Deuda Soberana",
      logo_emoji: "🏛️",
      descripcion:
        "Letra del Tesoro en pesos que ajusta por tipo de cambio oficial. Cobertura cambiaria sin divisas.",
      emisor: "Ministerio de Economía",
    },
    precio: {
      valor: 1320,
      moneda: "ARS",
      variacion_diaria_pct: 0.15,
      variacion_ytd_pct: 18.3,
      semana_52: { min: 1050, max: 1380 },
      volumen_operado_ars: 185000000,
    },
    letra_info: {
      vencimiento: "2025-10-17",
      dias_al_vencimiento: 219,
      tipo_ajuste: "Dólar linked",
      benchmark: {
        tipo: "Tipo de cambio oficial",
        valor_pct: null,
        spread_vs_benchmark_pct: null,
      },
    },
    noticias:
      "Demanda de cobertura cambiaria creció ante expectativas de unificación del tipo de cambio.",
  },
];
